import Head from "next/head";
import React, { useEffect } from "react";
import { GetStaticPropsContext } from "next";
import { Stack, Box } from "@mui/material";
import ProjectsSection from "@/components/sections/projects/ProjectsSection";
import carrier from "@/tmp/carrier.json";
import BookBoxSection from "@/components/sections/bookBox/BookBoxSection";
import CarrierSection from "@/components/sections/carrier/CarrierSection";
import AboutMeSection from "@/components/sections/aboutMe/AboutMeSection";
import { connectDB, client } from "@/utils/mongodb";
import type { Projects } from "@/schema/project";
import BreadCrumbs from "@/components/BreadCrumbs";
import { useRouter } from "next/router";

//
type Props = {
  projects: Projects;
};
export default function Home({ projects }: Props) {
  const router = useRouter();
  useEffect(() => {
    // Prefetch the project pages
    router.prefetch("/projects/[pid]");
  }, [router]);
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ ml: 2 }}>
        <BreadCrumbs items={null} />
      </Box>
      <Stack direction="column" spacing={3} justifyContent="center" alignItems="center">
        <ProjectsSection projects={projects} />
        <BookBoxSection />
        <CarrierSection carrier={carrier} />
        <AboutMeSection />
      </Stack>
    </>
  );
}

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  // Get all products
  const dbName = "Data";
  const projectsCollection = "projects";
  const carrierCollection = "carrier";
  let projects = null;

  try {
    // Connect to MongoDB
    await connectDB();
    // Access the specified database and collection
    const db = client.db(dbName);
    const collection = db.collection(projectsCollection);
    // Retrieve all documents in the collection
    projects = await collection.find().toArray();
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      projects: JSON.parse(JSON.stringify(projects)),
    },
    revalidate: false, //on demand revalidation
  };
}
