import Head from "next/head";
import { Container } from "@mui/material";
import ProjectsSection from "@/components/projects/ProjectsSection";
import projects from "@/tmp/projects.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ pt: 2, pb: 4, display: "flex", justifyContent: "left", flexDirection: "column" }}>
        <ProjectsSection projects={projects}/>
      </Container>
    </>
  );
}
